# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.preleva = channel.unary_unary(
                '/magazzino.Service/preleva',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.Item.FromString,
                )
        self.deposita = channel.unary_unary(
                '/magazzino.Service/deposita',
                request_serializer=service__pb2.Item.SerializeToString,
                response_deserializer=service__pb2.StringMessage.FromString,
                )
        self.svuota = channel.unary_stream(
                '/magazzino.Service/svuota',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.Item.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def preleva(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deposita(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def svuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'preleva': grpc.unary_unary_rpc_method_handler(
                    servicer.preleva,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.Item.SerializeToString,
            ),
            'deposita': grpc.unary_unary_rpc_method_handler(
                    servicer.deposita,
                    request_deserializer=service__pb2.Item.FromString,
                    response_serializer=service__pb2.StringMessage.SerializeToString,
            ),
            'svuota': grpc.unary_stream_rpc_method_handler(
                    servicer.svuota,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.Item.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'magazzino.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def preleva(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/magazzino.Service/preleva',
            service__pb2.Empty.SerializeToString,
            service__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deposita(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/magazzino.Service/deposita',
            service__pb2.Item.SerializeToString,
            service__pb2.StringMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def svuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/magazzino.Service/svuota',
            service__pb2.Empty.SerializeToString,
            service__pb2.Item.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
